import React from 'react';
import { FileText, X, CheckSquare, ListOrdered, Calendar, MessageSquare, AlertCircle } from 'lucide-react';

export function GroupSummaryModal({ isOpen, onClose, summary }) {
  if (!isOpen || !summary) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md animate-fadeIn">
      <div className="glass-panel w-full max-w-xl rounded-3xl p-6 sm:p-8 border border-purple-500/30 shadow-2xl relative space-y-6 bg-purple-950/20">
        
        <button
          onClick={onClose}
          className="absolute top-5 right-5 w-8 h-8 rounded-full glass-card flex items-center justify-center text-gray-400 hover:text-white"
        >
          <X className="w-4 h-4" />
        </button>

        {/* Modal Header */}
        <div className="flex items-center gap-3 border-b border-white/10 pb-4">
          <div className="w-10 h-10 rounded-2xl bg-purple-600/30 border border-purple-400/40 flex items-center justify-center text-purple-300">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-white font-heading">Today's Group Summary</h3>
            <p className="text-xs text-purple-300">Generated by PingX AI Engine</p>
          </div>
        </div>

        <div className="space-y-5 text-xs">
          
          {/* Summary Bullets */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-gray-300 uppercase tracking-wider flex items-center gap-1.5">
              <MessageSquare className="w-3.5 h-3.5 text-purple-400" /> Today's Highlights
            </h4>
            <div className="glass-card p-3 rounded-xl space-y-1.5 text-gray-200">
              {summary.todaysSummary?.map((item, i) => (
                <p key={i} className="flex items-start gap-2">
                  <span className="text-purple-400 font-bold">•</span>
                  {item}
                </p>
              ))}
            </div>
          </div>

          {/* Decisions */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-gray-300 uppercase tracking-wider flex items-center gap-1.5">
              <CheckSquare className="w-3.5 h-3.5 text-emerald-400" /> Key Decisions
            </h4>
            <div className="glass-card p-3 rounded-xl space-y-1.5 text-gray-200 border-emerald-500/20">
              {summary.decisions?.map((item, i) => (
                <p key={i} className="flex items-start gap-2">
                  <span className="text-emerald-400 font-bold">✓</span>
                  {item}
                </p>
              ))}
            </div>
          </div>

          {/* Action Tasks */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-gray-300 uppercase tracking-wider flex items-center gap-1.5">
              <ListOrdered className="w-3.5 h-3.5 text-blue-400" /> Action Items & Tasks
            </h4>
            <div className="glass-card p-3 rounded-xl space-y-1.5 text-gray-200 border-blue-500/20">
              {summary.tasks?.map((item, i) => (
                <p key={i} className="flex items-start gap-2">
                  <span className="text-blue-400 font-mono font-bold">[{i+1}]</span>
                  {item}
                </p>
              ))}
            </div>
          </div>

          {/* Important Messages */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-gray-300 uppercase tracking-wider flex items-center gap-1.5">
              <AlertCircle className="w-3.5 h-3.5 text-amber-400" /> Important Reminders
            </h4>
            <div className="glass-card p-3 rounded-xl text-amber-300 border-amber-500/20">
              {summary.importantMessages?.map((item, i) => (
                <p key={i}>{item}</p>
              ))}
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
